### ISSUE TITLE
Support for PHP 8?

### ISSUE THREAD

**Issue by gmazzap** [sirbrillig/phpcs-neutron-standard#85]
Right now, your composer.json says [` "php": "^7.0"`](https://github.com/Automattic/phpcs-neutron-standard/blob/master/composer.json#L37)

I'm trying to run tests for PHP 8 in some of my libraries, but that requirems make composer install fails.
Can you maybe change to `>=7.0`?

**Comment by sirbrillig** [comment]
That's a good question. I haven't had a chance to test these rules on PHP 8; can you confirm they work there? I seem to recall reading that PHPCS doesn't yet support PHP 8...

**Comment by sirbrillig** [comment]
If it's helpful at all, and it may not be, I deal with similar issues (in my case running tests on PHP 5.x) by having different composer.json files for different PHP environments and have my CI configured to use the appropriate one. This isn't a full solution, because it really just means that I don't use the linters that are unavailable on those environments, but it does let you skip them to run other tests.

**Comment by sirbrillig** [comment]
Should be fixed by https://github.com/Automattic/phpcs-neutron-standard/pull/86
